services:
  - type: web
    name: diary-app-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt && python -m prisma generate"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_CREDENTIALS_PATH
        value: ./firebase-credentials.json
      - key: UPLOAD_DIR
        value: ./uploads
    autoDeploy: true

